[build]
  functions = "api"  # Directory containing serverless functions

[functions]
  node_bundler = "esbuild"  # Default bundler for serverless functions

[[redirects]]
  from = "/"
  to = "/api/main/"
  status = 200